name: smarted
description: SmarTED client app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amazon_cognito_identity_dart_2: ^0.1.12+3
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/